### ISSUE TITLE
[DOC SUGGESTION]: error 404

### ISSUE THREAD

**Issue by bhyuu** [spatialsys/spatial-unity-sdk#34]
### Doc Page Links

https://toolkit.spatial.io/docs/components/trigger-event

### Explain Suggestion

at the bottom of the page the hyperlink for [Synced Animator](https://toolkit.spatial.io/docs/components/synced-animator) lead us to an error 404 page

**Comment by Jastman** [comment]
Thanks for letting us know! This link will be fixed soon. Here is the correct link to the Synced Animator docs:  [https://toolkit.spatial.io/docs/multiplayer/synced-animator](https://toolkit.spatial.io/docs/multiplayer/synced-animator)
