### ISSUE TITLE
[DOC SUGGESTION]: Watch Ad using Ad Service

### ISSUE THREAD

**Issue by andiCR** [spatialsys/spatial-unity-sdk#6]
### Doc Page Links

https://cs.spatial.io/api/SpatialSys.UnitySDK.IAdService.html

### Explain Suggestion

Added code sample to use the ad service's two functions.

### Code Suggestion

```csharp
void WatchAd()
{
    if (!SpatialBridge.adService.isSupported)
        return;
    
    SpatialBridge.adService.RequestAd(SpatialAdType.Rewarded).SetCompletedEvent(request =>
    {
        if (request.succeeded)
        {
            Debug.Log("Ad succeeded");
        }
    });
}
```

### Contribution Credit

Andres Cartin

### Spatial.io handle

andi

### Discord handle

andicr

**Comment by alanSherba** [comment]
added
