### ISSUE TITLE
[DOC SUGGESTION]: VisualScriptingUtility.TriggerCustomEvent

### ISSUE THREAD

**Issue by mccuskerkevin** [spatialsys/spatial-unity-sdk#7]
### Doc Page Links

https://cs.spatial.io/api/SpatialSys.UnitySDK.VisualScriptingUtility.TriggerCustomEvent.html

### Explain Suggestion

With so many spaces having been built with Visual Scripting, it would be helpful to include a simple example on how to use those script graphs with C#. In my simple example I set up a Sphere with a Spatial Interactable as a child. In the interactable's On Interact Event section, I made two entries - one for each of the example C# functions that raise a visual script event. The events simply print values to the Debug.LogWarning console.
![image](https://github.com/spatialsys/spatial-unity-sdk/assets/156005021/4c136005-c538-4e58-b475-752a5152faa4)
![image](https://github.com/spatialsys/spatial-unity-sdk/assets/156005021/7395e91e-b28e-403b-8ff6-b0f430170eaf)

Additionally, the "message" parameter of the TriggerCustomEvent function is misleading. I would have expected it to be something like "eventName", "vsEventName", or even "visualScriptEventName".

### Code Suggestion

```csharp
using SpatialSys.UnitySDK;
using UnityEngine;

public class ScriptWithFunctions : MonoBehaviour
{
    [SerializeField]
    GameObject objectWithScriptMachine;

    readonly string eventName = "RaisedFromCSharp";
    readonly string eventNameWithParameters = "RaisedFromCSharpWithParameters";

    public void RaiseVisualScriptingEvent()
    {
        VisualScriptingUtility.TriggerCustomEvent(objectWithScriptMachine, eventName);        
    }

    public void RaiseVisualScriptingEventWithParameters()
    {
        int param1 = 1;
        int param2 = 2;
        VisualScriptingUtility.TriggerCustomEvent(objectWithScriptMachine, eventNameWithParameters, param1, param2, this);
    }
}
```

**Comment by alanSherba** [comment]
Added a slightly less detailed example (not sure how to add an image currently 😅):

Also documented the rest of the class.

> Additionally, the "message" parameter of the TriggerCustomEvent function is misleading.

Agreed. Bug didnt change this in my update. 


![image](https://github.com/spatialsys/spatial-unity-sdk/assets/100000804/b76210cd-a2ee-4cfc-a375-2fd519feff8e)
